# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NAPOD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NAPOD
pod 'Kingfisher', '~> 7.1'
pod 'ProgressHUD', '~> 13.6'
end
